<a href="https://colab.research.google.com/github/xmfaizan/lstm-word_embed/blob/main/junk_news_classif.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
# dataset train.csv imported from kaggle - https://www.kaggle.com/c/fake-news/data#

In [1]:
import pandas as pd

In [30]:
df = pd.read_csv('train.csv')

In [31]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [32]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [33]:
df = df.dropna()  #Since it is text data

In [34]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [35]:
df.shape, df.isnull().sum()

((18285, 5),
 id        0
 title     0
 author    0
 text      0
 label     0
 dtype: int64)

In [36]:
X = df.drop('label',axis=1)

In [37]:
y= df['label']  #op

In [38]:
X.shape, y.shape

((18285, 4), (18285,))

In [39]:
import tensorflow as tf

In [40]:
tf.__version__

'2.15.0'

In [41]:
vocab_size=10000

In [42]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [43]:
msg = X.copy()

In [44]:
msg

id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
20795                              Jerome Hudson   
20796                           Benjamin Hoffman   
20797  Michael J. de la Merced and Rachel Abrams   
20798                                Alex Ansary   
20799                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
20795  Rapper T. I. unloaded on black celebrities who...  
20796  When the Green Bay Packers lost to the Washing...  
20797  The Macy’s of today grew from the union of sev...  
20798  NATO, Russia To Hold Parallel Exercises In Bal...  
20799    David Swanson is an author, activist, journa...  

[18285 rows x 4 columns]

In [45]:
msg.reset_index(inplace=True)

In [46]:
msg

index     id                                              title  \
0          0      0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1      1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2      2                  Why the Truth Might Get You Fired   
3          3      3  15 Civilians Killed In Single US Airstrike Hav...   
4          4      4  Iranian woman jailed for fictional unpublished...   
...      ...    ...                                                ...   
18280  20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
18281  20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
18282  20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
18283  20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
18284  20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2                             Consortiumnews.com   
3                                Jessica Purkiss   
4                                 Howard Portnoy   
...                                          ...   
18280                              Jerome Hudson   
18281                           Benjamin Hoffman   
18282  Michael J. de la Merced and Rachel Abrams   
18283                                Alex Ansary   
18284                              David Swanson   

                                                    text  
0      House Dem Aide: We Didn’t Even See Comey’s Let...  
1      Ever get the feeling your life circles the rou...  
2      Why the Truth Might Get You Fired October 29, ...  
3      Videos 15 Civilians Killed In Single US Airstr...  
4      Print \nAn Iranian woman has been sentenced to...  
...                                                  ...  
18280  Rapper T. I. unloaded on black celebrities who...  
18281  When the Green Bay Packers lost to the Washing...  
18282  The Macy’s of today grew from the union of sev...  
18283  NATO, Russia To Hold Parallel Exercises In Bal...  
18284    David Swanson is an author, activist, journa...  

[18285 rows x 5 columns]

In [47]:
import nltk
import re  #regular expressions

In [48]:
from nltk.corpus import stopwords

In [50]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [51]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer ##stemming purpose
ps = PorterStemmer()
corpus = []
for i in range(0, len(msg)):
    review = re.sub('[^a-zA-Z]', ' ', msg['title'][i])  #replace all the other special charac with blank space
    review = review.lower()
    review = review.split()

    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [52]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [53]:
corpus[100]

'snap share leap debut investor doubt valu vanish new york time'

In [54]:
ohe = [one_hot(words,vocab_size) for words in corpus]

In [55]:
ohe

[[1372, 7040, 4774, 4985, 8013, 6774, 5780, 6126, 6963, 9882],
 [8244, 9372, 9561, 1316, 4219, 7378, 5051],
 [3229, 1792, 3887, 7027],
 [3577, 1568, 548, 1782, 3008, 1934],
 [9635, 4219, 1101, 3811, 2989, 7406, 4219, 119, 8954, 6539],
 [2624,
  1166,
  9499,
  8581,
  8888,
  3959,
  8042,
  2327,
  9823,
  2850,
  2002,
  6315,
  7515,
  9905,
  5051],
 [8040, 3048, 5473, 7231, 2193, 9755, 7778, 729, 6120, 3013, 6564],
 [3621, 8852, 5098, 5771, 1906, 1497, 3959, 5413, 6120, 3013, 6564],
 [7406, 2485, 7014, 8006, 141, 5480, 3780, 1625, 3959, 4743],
 [8149, 7961, 83, 7779, 2468, 3272, 7747, 6040],
 [7678, 4679, 6050, 3003, 7090, 3266, 3701, 4607, 6130, 9572, 1255],
 [1782, 3629, 8013, 5480, 3959, 1906],
 [4075, 3712, 478, 2757, 4851, 2637, 8657, 7879, 9593],
 [5991, 3213, 8615, 9413, 6133, 4089, 8324, 6120, 3013, 6564],
 [7646, 5328, 5488, 7724, 9770, 6120, 3013, 6564],
 [273, 8762, 7991, 1484, 2890, 4085, 3809, 6809, 2866, 3641],
 [7638, 8438, 9372],
 [4422, 3563, 6841, 882, 3959, 4308

In [56]:
corpus[200], ohe[200]

('la expresi n lo siguient ya es la utilizada lo siguient en el castellano',
 [7958,
  8906,
  1981,
  1018,
  1380,
  8736,
  9514,
  7958,
  9528,
  1018,
  1380,
  653,
  3235,
  5936])

In [57]:
max_sentl = 18

In [58]:
emdb_docs = pad_sequences(ohe,padding='post',maxlen=max_sentl)
emdb_docs

array([[1372, 7040, 4774, ...,    0,    0,    0],
       [8244, 9372, 9561, ...,    0,    0,    0],
       [3229, 1792, 3887, ...,    0,    0,    0],
       ...,
       [2058, 5831, 4303, ...,    0,    0,    0],
       [1474, 1906, 4276, ...,    0,    0,    0],
       [8065, 2044, 8421, ...,    0,    0,    0]], dtype=int32)

In [59]:
emdb_docs[300]

array([8231,   21, 4158, 8639, 7920, 3465, 8145, 3672,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0], dtype=int32)

In [60]:
#Model
embedding_vector_features=50 #features representation
model=Sequential()
model.add(Embedding(vocab_size,embedding_vector_features,input_length= 18))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))  #o/p is binary
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 18, 50)            500000    
                                                                 
 lstm (LSTM)                 (None, 100)               60400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 560501 (2.14 MB)
Trainable params: 560501 (2.14 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [62]:
len(emdb_docs), y.shape

(18285, (18285,))

In [63]:
import numpy as np

In [64]:
x_final = np.array(emdb_docs)
y_final = np.array(y)

In [65]:
x_final.shape

(18285, 18)

In [67]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x_final, y_final, test_size=0.33, random_state=20)

In [68]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=8,batch_size=32)

Epoch 1/8
383/383 [==============================] - 19s 40ms/step - loss: 0.2563 - accuracy: 0.8812 - val_loss: 0.1819 - val_accuracy: 0.9261
Epoch 2/8
383/383 [==============================] - 4s 9ms/step - loss: 0.1165 - accuracy: 0.9564 - val_loss: 0.1931 - val_accuracy: 0.9226
Epoch 3/8
383/383 [==============================] - 3s 8ms/step - loss: 0.0734 - accuracy: 0.9726 - val_loss: 0.2534 - val_accuracy: 0.9133
Epoch 4/8
383/383 [==============================] - 4s 11ms/step - loss: 0.0429 - accuracy: 0.9837 - val_loss: 0.2861 - val_accuracy: 0.9168
Epoch 5/8
383/383 [==============================] - 3s 8ms/step - loss: 0.0254 - accuracy: 0.9920 - val_loss: 0.4411 - val_accuracy: 0.9122
Epoch 6/8
383/383 [==============================] - 3s 7ms/step - loss: 0.0244 - accuracy: 0.9922 - val_loss: 0.4452 - val_accuracy: 0.9132
Epoch 7/8
383/383 [==============================] - 2s 6ms/step - loss: 0.0181 - accuracy: 0.9947 - val_loss: 0.3439 - val_accuracy: 0.9181
Epoch 8/8


In [69]:
y_pred=model.predict(X_test)

189/189 [==============================] - 1s 4ms/step


In [70]:
y_pred=np.where(y_pred > 0.5, 1,0) ##AUC ROC Curve

In [71]:
from sklearn.metrics import confusion_matrix

In [73]:
confusion_matrix(y_test,y_pred)

array([[3029,  333],
       [ 167, 2506]])

In [74]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9171499585749793

In [76]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92      3362
           1       0.88      0.94      0.91      2673

    accuracy                           0.92      6035
   macro avg       0.92      0.92      0.92      6035
weighted avg       0.92      0.92      0.92      6035

