<a href="https://colab.research.google.com/github/xmfaizan/lstm-word_embed/blob/main/LSTM_Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [6]:
from tensorflow.keras.preprocessing.text import one_hot #allows for OHE

In [7]:
#sentences

sent=[  'the glass of coke',
     'the glass of juice',
     'the cup of tea',
    'He is a good boy',
     'I am a good programmer',
     'understand the meaning of life',
     'the girls are good']

In [8]:
sent

['the glass of coke',
 'the glass of juice',
 'the cup of tea',
 'He is a good boy',
 'I am a good programmer',
 'understand the meaning of life',
 'the girls are good']

In [10]:
#vocab
vocab_size=10000

In [12]:
onehot_ind=[one_hot(words,vocab_size)for words in sent]
print(onehot_ind)   #Catching the indexes from OHE

[[3515, 812, 7000, 7928], [3515, 812, 7000, 847], [3515, 4777, 7000, 159], [1421, 2962, 1475, 1175, 9165], [166, 2302, 1475, 1175, 7076], [150, 3515, 7436, 7000, 7059], [3515, 7547, 5922, 1175]]


In [13]:
#All my sentences should have the same dimensions - post and pre padding

In [14]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [15]:
import numpy as np

In [17]:
## pre padding
max_sentl=8
emb_docs=pad_sequences(onehot_ind,padding='pre',maxlen=max_sentl)
print(emb_docs)

[[   0    0    0    0 3515  812 7000 7928]
 [   0    0    0    0 3515  812 7000  847]
 [   0    0    0    0 3515 4777 7000  159]
 [   0    0    0 1421 2962 1475 1175 9165]
 [   0    0    0  166 2302 1475 1175 7076]
 [   0    0    0  150 3515 7436 7000 7059]
 [   0    0    0    0 3515 7547 5922 1175]]


In [18]:
#feature representation dimension = 10
dim = 10

In [20]:
model = Sequential()
model.add(Embedding(vocab_size,10,input_length=max_sentl))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
emb_docs[0]

array([   0,    0,    0,    0, 3515,  812, 7000, 7928], dtype=int32)

In [23]:
model.predict(emb_docs[0])    #8x10

1/1 [==============================] - 0s 148ms/step


array([[ 0.00979299, -0.00422567, -0.02957232,  0.04753459, -0.00157921,
        -0.02546653, -0.0179431 , -0.00158783,  0.03129517,  0.04153954],
       [ 0.00979299, -0.00422567, -0.02957232,  0.04753459, -0.00157921,
        -0.02546653, -0.0179431 , -0.00158783,  0.03129517,  0.04153954],
       [ 0.00979299, -0.00422567, -0.02957232,  0.04753459, -0.00157921,
        -0.02546653, -0.0179431 , -0.00158783,  0.03129517,  0.04153954],
       [ 0.00979299, -0.00422567, -0.02957232,  0.04753459, -0.00157921,
        -0.02546653, -0.0179431 , -0.00158783,  0.03129517,  0.04153954],
       [ 0.01104997, -0.02445217, -0.04800688,  0.04352845, -0.02743444,
        -0.00740352, -0.03878438, -0.03386714,  0.01550523, -0.00873412],
       [-0.01540273,  0.00916119, -0.01240401,  0.03099262,  0.00525229,
         0.04783168, -0.02621784, -0.00489161, -0.03152584,  0.01904949],
       [ 0.02821504,  0.03049174, -0.01444542,  0.04880256, -0.03073187,
         0.0303697 , -0.00471411,  0.03144183

In [24]:
model.predict(emb_docs)

1/1 [==============================] - 0s 32ms/step


array([[[ 9.79299471e-03, -4.22567129e-03, -2.95723211e-02,
          4.75345887e-02, -1.57921389e-03, -2.54665259e-02,
         -1.79430954e-02, -1.58783048e-03,  3.12951691e-02,
          4.15395387e-02],
        [ 9.79299471e-03, -4.22567129e-03, -2.95723211e-02,
          4.75345887e-02, -1.57921389e-03, -2.54665259e-02,
         -1.79430954e-02, -1.58783048e-03,  3.12951691e-02,
          4.15395387e-02],
        [ 9.79299471e-03, -4.22567129e-03, -2.95723211e-02,
          4.75345887e-02, -1.57921389e-03, -2.54665259e-02,
         -1.79430954e-02, -1.58783048e-03,  3.12951691e-02,
          4.15395387e-02],
        [ 9.79299471e-03, -4.22567129e-03, -2.95723211e-02,
          4.75345887e-02, -1.57921389e-03, -2.54665259e-02,
         -1.79430954e-02, -1.58783048e-03,  3.12951691e-02,
          4.15395387e-02],
        [ 1.10499747e-02, -2.44521741e-02, -4.80068810e-02,
          4.35284488e-02, -2.74344441e-02, -7.40351528e-03,
         -3.87843847e-02, -3.38671356e-02,  1.550522